import { z } from "zod";

// AWS Landing Zone Configuration Types
export const landingZoneConfigSchema = z.object({
  size: z.enum(["very-small", "small", "medium", "large"]),
  name: z.string(),
  description: z.string(),
  accountStructure: z.string(),
  organizationalStructure: z.string(),
  guardrails: z.string(),
  accessManagement: z.string(),
  networking: z.string(),
  automation: z.string(),
  security: z.string(),
  monitoring: z.string(),
  defaultVMs: z.number(),
  defaultStorageTB: z.number(),
  infraCostPerMonth: z.number(),
  professionalServicesCost: z.number(),
  managedServicesCostPerVM: z.number(),
  managedServicesCostPerTB: z.number(),
});

export const costCalculationSchema = z.object({
  selectedConfig: z.string(),
  customVMs: z.number().optional(),
  customStorageTB: z.number().optional(),
});

export type LandingZoneConfig = z.infer<typeof landingZoneConfigSchema>;
export type CostCalculation = z.infer<typeof costCalculationSchema>;

// AWS Landing Zone configurations data
export const landingZoneConfigurations: LandingZoneConfig[] = [
  {
    size: "very-small",
    name: "Very Small Customers (1-2 accounts)",
    description: "Perfect for startups and small businesses with minimal AWS infrastructure needs",
    accountStructure: "Management account + 1 workload account",
    organizationalStructure: "Minimal AWS Organizations structure with Root and Workloads OU",
    guardrails: "Basic SCPs and manual AWS Config rules",
    accessManagement: "IAM users and groups with basic IAM policies", 
    networking: "Simple VPC setup with basic VPN for on-premises connectivity (if needed)",
    automation: "Simple CloudFormation templates and basic AWS CLI scripts",
    security: "GuardDuty (optional), basic IAM policies, manual security checks",
    monitoring: "Basic CloudWatch alarms, CloudTrail enabled in management account",
    defaultVMs: 2,
    defaultStorageTB: 1,
    infraCostPerMonth: 500,
    professionalServicesCost: 15000,
    managedServicesCostPerVM: 150,
    managedServicesCostPerTB: 100,
  },
  {
    size: "small",
    name: "Small Customers (3-5 accounts/apps)",
    description: "Ideal for growing companies with multiple applications and environments",
    accountStructure: "Management, Log archive, Audit accounts + 1+ workload accounts",
    organizationalStructure: "Basic AWS Organizations structure with Root, Core OU (Log, Audit), and Workloads OU",
    guardrails: "Basic SCPs, Control Tower mandatory guardrails, few selected strongly recommended guardrails",
    accessManagement: "AWS IAM Identity Center with basic permission sets and local user management",
    networking: "Basic VPC setup, AWS Transit Gateway for inter-VPC connectivity, Simple Direct Connect or VPN for on-premises",
    automation: "Basic CloudFormation templates, AWS Systems Manager for patching and maintenance",
    security: "GuardDuty, basic IAM policies, AWS Security Hub (basic features), Amazon Inspector for vulnerability assessments",
    monitoring: "Basic CloudWatch dashboards, CloudTrail logs in central account, Simple SNS/SES alerting",
    defaultVMs: 8,
    defaultStorageTB: 5,
    infraCostPerMonth: 2000,
    professionalServicesCost: 35000,
    managedServicesCostPerVM: 180,
    managedServicesCostPerTB: 120,
  },
  {
    size: "medium",
    name: "Medium Customers (6-15 accounts/apps)",
    description: "Suitable for established businesses with complex multi-environment setups",
    accountStructure: "Management, Log archive, Audit, Shared services accounts + Separate Dev, Test, Prod accounts + business unit/app accounts",
    organizationalStructure: "More complex OU structure with Root, Core OU (Log, Audit, Shared Services), Prod OU, Non-Prod OU, Sandbox OU",
    guardrails: "SCPs for each OU, All Control Tower guardrails, Custom AWS Config rules, Tag policies",
    accessManagement: "AWS IAM Identity Center with integration to customer's identity provider (e.g., Azure AD), Custom permission sets, Attribute-based access control (ABAC)",
    networking: "Hub-and-spoke with AWS Transit Gateway, Shared services VPC, Transit Gateway Network Manager, AWS Network Firewall, Direct Connect with backup VPN",
    automation: "CloudFormation StackSets, AWS Systems Manager for config management, Basic CI/CD pipelines for infrastructure",
    security: "GuardDuty with automated remediation, Security Hub with custom actions, Network Firewall, AWS Config advanced queries, Amazon Detective for security investigations, AWS Certificate Manager for SSL/TLS",
    monitoring: "Enhanced CloudWatch dashboards and alarms, CloudTrail logs with organization trail, Log aggregation in centralized account, Basic log analytics",
    defaultVMs: 25,
    defaultStorageTB: 15,
    infraCostPerMonth: 8000,
    professionalServicesCost: 75000,
    managedServicesCostPerVM: 200,
    managedServicesCostPerTB: 140,
  },
  {
    size: "large",
    name: "Large Customers (15+ accounts/apps)",
    description: "Enterprise-grade solution for large organizations with extensive AWS infrastructure",
    accountStructure: "Management, Log archive, Audit, Security, Shared services, Network accounts + Separate Dev, Test, Stage, Prod accounts + business unit/department/app accounts",
    organizationalStructure: "Comprehensive OU structure with Root, Infrastructure OU (Core, Network, Security), Prod OU (by business unit), Non-Prod OU (by business unit), Sandbox OU, Suspended OU",
    guardrails: "Granular SCPs for each OU, All Control Tower guardrails, Extensive custom AWS Config rules, Custom Lambda functions for advanced policies, Comprehensive tag policies and enforcement",
    accessManagement: "AWS IAM Identity Center with integration to enterprise identity management, Fine-grained permission sets, Advanced ABAC, Custom IAM policies and roles, Automated access reviews",
    networking: "Complex architecture with Transit Gateway, Multiple Transit Gateways for isolation, SD-WAN integration, AWS Network Firewall and Gateway Load Balancer, AWS WAF and Shield Advanced, Global Accelerator for optimized routing, Multiple Direct Connect connections with redundancy",
    automation: "Control Tower Account Factory for Terraform (AFT), Custom account vending machine, Advanced CI/CD pipelines for infrastructure and applications, AWS Systems Manager for comprehensive ops management, Custom automation runbooks",
    security: "GuardDuty with custom threat detection, Security Hub with multi-account aggregation, Network Firewall with complex rule sets, WAF with custom rules and managed rule sets, AWS Macie for sensitive data discovery, AWS KMS for centralized key management, Third-party security tool integration (e.g., Splunk, CrowdStrike)",
    monitoring: "Comprehensive monitoring with CloudWatch, CloudTrail, and X-Ray, Centralized logging with Kinesis Data Firehose, Advanced log analytics with Elasticsearch Service, Custom metrics and logs collection",
    defaultVMs: 100,
    defaultStorageTB: 50,
    infraCostPerMonth: 25000,
    professionalServicesCost: 150000,
    managedServicesCostPerVM: 250,
    managedServicesCostPerTB: 160,
  },
];
